name: 'Blue Octocat'
description: 'Github action for getting Telegram notifications'
author: 'MuhammadMP97'

branding:
  color: 'blue'

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

inputs:
  bot_token:
    required: true
  user_id:
    required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    using: 'composite'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const botToken = core.getInput('bot_token')
            const userId = core.getInput('user_id')

            if (!botToken) {
              return core.setFailed('BOT_TOKEN is not defined!');
            }

            if (!userId) {
              return core.setFailed('USER_ID is not defined!');
            }
          
            const subject = context.payload.pull_request ?? context.payload.issue;

            const type = context.payload.pull_request ? 'pull request' : 'issue';
            const text = `🙋‍♂️ A new <b>${type}</b> by <b>${subject.user.login}</b>:\n<a href="${subject.html_url}">${subject.title}</a>`;

            const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
              method: 'POST',
              headers: {'Content-Type': 'application/json'},
              body: JSON.stringify({
                text: text,
                chat_id: userId,
                parse_mode: 'html'
              })
            });

            if (!response.ok) {
              const jsonResponse = await response.json();
              core.setFailed(jsonResponse);
            }
