name: 'Blue Octocat'
description: 'Github action for getting Telegram notifications'
author: 'MuhammadMP97'

branding:
  color: 'blue'

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

inputs:
  bot_token:
    required: true
  user_id:
    required: true

runs:
  using: 'node20'
  main: 'action.js'
